# Generated by Django 5.1.4 on 2024-12-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.CharField(default='Dizel', max_length=100),
            preserve_default=False,
        ),
    ]
